# Generated by Django 5.1.2 on 2024-10-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='archivos_aula',
        ),
        migrations.AddField(
            model_name='aula',
            name='rchivos_aula',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='apellidos',
            field=models.CharField(default='Apellidos', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='documento',
            field=models.IntegerField(),
        ),
    ]
