# Generated by Django 5.1.2 on 2024-10-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_aula_archivos_aula_aula_rchivos_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
