# Generated by Django 5.1.2 on 2024-10-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_teacher_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='rchivos_aula',
            new_name='archivos_aula',
        ),
    ]
