# Generated by Django 5.1.2 on 2024-10-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_rchivos_aula_aula_archivos_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='archivos_aula',
        ),
    ]
