# Generated by Django 5.1.2 on 2024-10-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_aula_archivos_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='aula_id',
            field=models.IntegerField(default=0),
        ),
    ]
