# Generated by Django 5.1.2 on 2024-10-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aula_aula_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
