# Generated by Django 5.1.2 on 2024-11-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
