# Generated by Django 5.1.2 on 2024-11-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_teacher_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False},
        ),
    ]
