# Generated by Django 5.1.2 on 2024-11-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=300, null=True)),
                ('session_date_start', models.TimeField(blank=True, null=True)),
                ('session_date_end', models.TimeField(blank=True, null=True)),
                ('session_description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
    ]
