# Generated by Django 5.1.2 on 2024-11-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        ('teacher', '0002_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_name', models.TextField(max_length=100)),
                ('session_material', models.TextField(max_length=100)),
                ('session_description', models.TextField(max_length=100)),
                ('qrCode', models.ImageField(blank=True, upload_to='')),
                ('session_date_start', models.DateField(null=True)),
                ('session_date_end', models.DateField(null=True)),
                ('session_hour', models.TimeField(null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='teacher.teacher')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.DeleteModel(
            name='sesion',
        ),
    ]
