# Generated by Django 5.1.2 on 2024-11-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_delete_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='qrCode',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_hour',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_material',
        ),
        migrations.RemoveField(
            model_name='session',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='session',
            name='session_date_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_date_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
