# Generated by Django 5.1.2 on 2024-11-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_remove_session_qrcode_remove_session_session_hour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'managed': False},
        ),
    ]
