# Generated by Django 5.1.2 on 2024-11-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rol_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
    ]
