# Generated by Django 5.1.2 on 2024-11-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
